---
- hosts: all
  become: true
  tasks:
  - name: Work out the distribution
    command: lsb_release -sc
    register: distribution

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution.stdout }} stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - containerd.io=1.2.10-3
      - docker-ce=5:19.03.6~3-0~ubuntu-{{ distribution.stdout }}
      - docker-ce-cli=5:19.03.6~3-0~ubuntu-{{ distribution.stdout }}

  - name: Use "systemd" as the Docker cgroup driver
    blockinfile:
      path: /etc/docker/daemon.json
      create: yes
      marker: ""
      block: |2
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }

  - name: Create Docker service directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: '0755'

  - name: Restart Docker service
    service:
      name: docker
      daemon_reload: yes
      state: restarted
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  # Kubelet will not start if the system has swap enabled, so we are disabling swap
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  # Installing kubelet, kubeadm and kubectl
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-{{ distribution.stdout }} main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Configure node ip
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}"'
      regexp: 'KUBELET_EXTRA_ARGS='
      insertafter: '\[Service\]'
      state: present

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  # Join the nodes to the Kubernetes cluster   
  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  # Setup a handler for checking Docker daemon
  handlers:
    - name: docker status
      service: name=docker state=started
